"""Added gallery 

Revision ID: a6512c12ed14
Revises: da5fc727b724
Create Date: 2025-05-18 10:41:39.289345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6512c12ed14'
down_revision = 'da5fc727b724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('gallery_photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.drop_constraint('gallery_photo_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('display_order')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('gallery_photo_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('likes')
        batch_op.drop_column('order')

    with op.batch_alter_table('gallery_category', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
