"""Add social media usernames to PersonalityOfTheWeek

Revision ID: c9b3acc30c17
Revises: a6512c12ed14
Create Date: 2025-05-18 13:32:34.189827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b3acc30c17'
down_revision = 'a6512c12ed14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personality_of_the_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitter', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personality_of_the_week', schema=None) as batch_op:
        batch_op.drop_column('linkedin')
        batch_op.drop_column('instagram')
        batch_op.drop_column('facebook')
        batch_op.drop_column('twitter')

    # ### end Alembic commands ###
