"""Added delete functionality

Revision ID: da5fc727b724
Revises: 18b400b80412
Create Date: 2025-05-17 01:36:58.473391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5fc727b724'
down_revision = '18b400b80412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personality_of_the_week', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personality_of_the_week', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
